"""Initial migration

Revision ID: 2b113e08a643
Revises: 
Create Date: 2024-11-24 05:21:55.815334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b113e08a643'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('receipt_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_expense_category', 'expense_category', ['category_id'], ['id'])

    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('expense_split', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('avatar')
        batch_op.drop_column('timezone')
        batch_op.drop_column('currency')
        batch_op.drop_column('phone')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('expense_split', schema=None) as batch_op:
        batch_op.drop_column('percentage')

    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expense_category', type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('category_id')
        batch_op.drop_column('notes')
        batch_op.drop_column('receipt_image')
        batch_op.drop_column('currency')
        batch_op.drop_column('split_type')

    # ### end Alembic commands ###
