"""Add is_admin to GroupMembership model

Revision ID: 8ad665ba7ea5
Revises: 9304a5fbd43e
Create Date: 2024-11-24 06:41:43.958969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad665ba7ea5'
down_revision = '9304a5fbd43e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_membership', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
