"""Add creator_id to Group model

Revision ID: 9304a5fbd43e
Revises: 2b113e08a643
Create Date: 2024-11-24 06:39:18.436816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9304a5fbd43e'
down_revision = '2b113e08a643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_group_creator_id', 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint('fk_group_creator_id', type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
