from .auth import auth as auth_bp
from .main import main as main_bp
from .profile import profile as profile_bp
from .expense import expense as expense_bp
from .group import group as group_bp
from .settlement import settlement as settlement_bp
from .statistics import statistics as statistics_bp
from .activity import activity as activity_bp
from .insights import insights as insights_bp
from .advanced_analytics import advanced as advanced_bp
from .budget_analytics import budget_analytics as budget_analytics_bp
from .category import category as category_bp
from .stats import stats as stats_bp
from .reports import reports as reports_bp
from .expenses import expenses as expenses_bp
from .settlements import settlements as settlements_bp
from .budget import budget as budget_bp
from .recurring import recurring as recurring_bp
from .analytics import analytics as analytics_bp
from .dashboard import dashboard as dashboard_bp
